# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0003_comment_poster'),
        ('GroupsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='CommentsApp.Comment'),
        ),
    ]
