# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0002_auto_20161208_1336'),
        ('GroupsApp', '0002_remove_group_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='ProjectsApp.Project'),
        ),
    ]
