# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0003_comment_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='group',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='poster',
        ),
    ]
