# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0005_auto_20161208_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='university_name',
            new_name='university',
        ),
    ]
