# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0008_student_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='is_engineer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_teacher',
            field=models.BooleanField(default=True),
        ),
    ]
