# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0012_student_university'),
        ('AuthenticationApp', '0004_auto_20161208_0044'),
    ]

    operations = [
    ]
