# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0005_auto_20161208_0507'),
        ('UniversitiesApp', '0007_remove_university_professors'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='professors',
            field=models.ManyToManyField(to='AuthenticationApp.Teacher'),
        ),
    ]
