# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0008_university_professors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='professors',
        ),
    ]
