# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0012_student_university'),
        ('UniversitiesApp', '0010_university_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.Teacher'),
        ),
    ]
