# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0011_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='university',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='AuthenticationApp.Teacher'),
        ),
    ]
